C
C  $Id$
C
      DOUBLE PRECISION  USSIG, TOLIC, TOLSG, RMVAL
      INTEGER           NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMI/   NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMD/   USSIG, TOLIC, TOLSG, RMVAL
