set(CTEST_PROJECT_NAME "UVCDAT")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "http://uv-cdat.llnl.gov")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=UVCDAT")
set(CTEST_DROP_SITE_CDASH TRUE)
