#!/bin/sh
echo 'A message about /dev/null not being a regular file can be ignored here.'
echo 'Detailed log in libcdms/libcdms.LOG'
echo "CFLAGS:"$CFLAGS
current_dir=$(dirname $0)
(${current_dir}/cdms.sh $* > ${BUILD_DIR}/logs/libcdms.LOG) || exit 1

