version: 2

jobs:
  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - pwd
      - git clone -b validateNightly https://github.com/UV-CDAT/uvcdat
      - cd uvcdat
      - python3 scripts/install_nightly.py -w test_nightly

