defaults: &defaults
  working_directory: /tmp
 
version: 2
jobs:
  build:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - run: mkdir -p workspace
      - run:
          name: CloneUvcdatCode
          command: git clone -b validateNightly git@github.com:UV-CDAT/uvcdat workspace
      - run:
          name: InstallNightlyCdat
          command: python uvcdat/scripts/install_nightly.py -w workspace/test_nightly
      - run: echo "Done installing nightly"
      - run: ls test_nightly/miniconda/envs

      - persist_to_workspace:
          root: workspace
          paths:
	    - test_nightly
            - uvcdat

  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: echo "run testsuite...."
      - run: |
          if [[ -d /tmp/workspace/test_nightly ]]; then
	    echo "It worked!!!"
	  else
	    echo "It does not work!!"; exit 1
	  fi      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

