version: 2

jobs:
  build:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - run:
          name: CloneUvcdatCode
          command: git clone -b validateNightly git@github.com:UV-CDAT/uvcdat
      - run:
          name: InstallNightlyCdat
          command: python scripts/install_nightly.py -w test_nightly

  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "run testsuite...step1..."   
      - run: echo "run testsuite...step2..."   
 
workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
