version: 2

aliases:

  - &setup
    |
      - run: echo "...in setup...1"
      - run: echo "...in setup...2"


jobs:
  macos_nightly:
    machine:
      xcode:
        version: 7.2
      python:
        version: 3.6.0
    working_directory: /tmp
    environment:
      - PYTHON_VERSION: 'py2'
    steps:
      - run: echo "..macos Nightly..."
      - run: uname -a      
      - run: *setup

  linux_nightly:
    machine:
      image: circleci/classic:latest
    working_directory: ~/workspace
    environment:
      - PYTHON_VERSION: 'py3'
    steps:
      - run: echo "...linux Nightly..."
      - run: uname -a
      - run: *setup
workflows:
  version: 2
  nightly:
    jobs:
      - macos_nightly
      - linux_nightly


