version: 2

jobs:
  macos_nightly:
    machine:
      xcode:
        version: 7.2
      python:
        version: 3.6.0
    working_directory: /tmp
    steps:
      - run: echo "..macos Nightly..."
  linux_nightly:
    machine:
      image: circleci/classic:latest
    working_directory: ~/workspace
    steps:
      - run: echo "...linux Nightly..."
workflows:
  version: 2
  nightly:
    jobs:
      - macos_nightly
      - linux_nightly


