version: 2

jobs:
   build:
      machine:
         xcode:
            version: 7.2
      steps:
         - run: echo "Install nightly..."

   test:
      machine:
         xcode:
            version: 7.2       
      steps:
         - run: echo "run testsuites..."
   
workflows:
   version: 2
   build_and_test:
      jobs:
         - build
	 - test