version: 2

jobs:
  build:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - git clone -b validateNightly https://github.com/UV-CDAT/uvcdat
      - python3 scripts/install_nightly.py -w test_nightly

  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "run testsuite...step1..."   
      - run: echo "run testsuite...step2..."   
 
workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
