ersion: 2

jobs:
  macos_build:
    machine:
      xcode:
        version: 7.2
      python:
        version: 3.6.0
    working_directory: /tmp
    steps:
      - run: echo "...macos build..."

  linux_build:
    docker:
      - image: ubuntu-14.04-XXL-1325-0ccc9ce
    working_directory: /tmp
    steps:
      - run: echo "...machine build..."
      - run: uname -a


workflows:
  version: 2
  nightly:
    jobs:
      macos_build
      linux_build





