version: 2

jobs:
  build:
    machine:
      xcode:
        version: 7.2
      python:
        version: 3.6.0
    working_directory: /tmp
    steps:
      - run: echo "Install nightly..."
  test:
    machine:
      xcode:
        version: 7.2
    working_directory: ~/workspace
    steps:
      - run: echo "...test..."
workflows:
  version: 2
  nightly:
    jobs:
      - build
      - test


