version: 2

jobs:
  build:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - run:
          name: CloneUvcdatCode
          command: git clone -b validateNightly git@github.com:UV-CDAT/uvcdat
      - run:
          name: InstallNightlyCdat
          command: python uvcdat/scripts/install_nightly.py -w test_nightly
      - run: echo "Done installing nightly"
      - run: ls test_nightly/miniconda/envs
  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "run testsuite...step1..."   
      - run: echo "run testsuite...step2..."   
      - run: 
          name: RunCdmsTest
          command: python uvcdat/scripts/run_testsuite.py -w test_nightly -p 'py2' -t 'cdms'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
