version: 2

jobs:
   install_nightly:
      machine:
         xcode:
            version: 7.2
      steps:
         - run: echo "Install nightly..."

   run_testsuites:
      machine:
         xcode:
            version: 7.2       
      steps:
         - run: echo "run testsuites..."
   
workflows:
   version: 2
   validate_nightly
      jobs:
         - install_nightly
         - run_testsuites:
              requires:
	         - install_nightly