defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
  build:
    machine:
      xcode:
        version: 7.2
    steps:
      - run: echo "Install nightly..."
      - run: mkdir -p workspace
      - run:
          name: CloneUvcdatCode
          command: git clone -b validateNightly git@github.com:UV-CDAT/uvcdat workspace
      - run:
          name: InstallNightlyCdat
          command: python uvcdat/scripts/install_nightly.py -w workspace/test_nightly
      - run: echo "Done installing nightly"
      - run: ls test_nightly/miniconda/envs

      - persist_to_workspace:
          root: workspace
          paths:
	    - test_nightly
            - uvcdat

  test:
    machine:
      xcode:
        version: 7.2
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: echo "run testsuite...."
      - run: 
          name: RunCdmsTest
          command: ls /tmp/workspace/test_nightly
          #command: python /tmp/workspace/uvcdat/scripts/run_testsuite.py -w /tmp/workspace/test_nightly -p 'py2' -t 'cdms'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
