#!/usr/bin/env sh
version=`more ../../version`

MATPLOTLIB_MAJOR=0
MATPLOTLIB_MINOR=98
MATPLOTLIB_PATCH=4

if (test "$1" = "--debug") then
    D="--debug";
    OPT=-g; 
    shift
else
    D="";
    OPT=${OPT:=-O}
fi
export OPT

if (test ! -d $1) then
    echo -n "$1 is not a directory; create it? (y/[n])";
    y='n'
    read y;
    if (test ${y} = 'y') then
        mkdir $1; mkdir $1/bin; mkdir $1/lib; mkdir $1/include
        if (test ! -d $1) then
            echo "Could not create $1, installation aborted.";
            exit 1
        fi
    else
        echo 'Installation aborted.';
        exit 1
    fi
fi
prefix=`(cd $1;pwd)`
if (test "$2" = "" ) then
  pyprefix=${prefix}
else
  pyprefix=`(cd $2;pwd)`
fi

if (test ! -d build) then
    # Unpack everything into build
    mkdir build
    /bin/cp *.gz build
    cd build
    chmod +w *.gz 
    for x in *.gz; 
    do 
        echo "$x"; 
        gunzip -f $x;
        tar xf `basename $x .gz`;
        /bin/rm -f `basename $x .gz`
    done
    cd ..
fi
cd build
echo "Installation to ${prefix}"
# Make sure /usr/bin/env etc. finds 'ourselves'
PATH="${prefix}/bin:${PATH}"; export PATH
if test `${pyprefix}/bin/python -c "cmd = 'try:\n  import matplotlib\n  print 0\nexcept:\n  print 1'; exec(cmd)"` = "1" ; then
  echo "could not import need to build"
else
  if test `${pyprefix}/bin/python -c "import matplotlib ; print matplotlib.__version__.split('.')[0]"` -gt ${MATPLOTLIB_MAJOR}  ; then
    echo "no need to build major version of your matplotlib is greater than min required"
    exit;
  else
    if test `${pyprefix}/bin/python -c "import matplotlib ; print matplotlib.__version__.split('.')[1]"` -gt ${MATPLOTLIB_MINOR}  ; then
      echo "no need to build minor version of your matplotlib is greater than min required (major is identical)"
      exit;
    else
      if test `${pyprefix}/bin/python -c "import matplotlib ; print matplotlib.__version__.split('.')[2]"` -ge ${MATPLOTLIB_PATCH}  ; then
	echo "no need to build patch version of your matplotlib is greater than min required (major and minor are identical)"
	exit;
      fi
    fi
  fi
echo "building"
fi

cd matplotlib-*; \
cp -f ../../setup.pcmdi.py setup.py ; \
${pyprefix}/bin/python setup.py build ${D} install --prefix=${prefix} ;
