// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef LabelNodeMenu_h
#define LabelNodeMenu_h
#include <fltk/Window.h>
#include "FLTKNodeMenu.h"
#include "VisusLabelNode.h"
#include <fltk/TextEditor.h>
#include <fltk/Button.h>
#include <fltk/Group.h>

class LabelNodeMenu : public FLTKNodeMenu<pVisusLabelNode>  {
public:
  fltk::Window* createWindow();
  fltk::Window *mMenuWindow;
    fltk::TextEditor *mTextEditor;
private:
    inline void cb_mTextEditor_i(fltk::TextEditor*, void*);
    static void cb_mTextEditor(fltk::TextEditor*, void*);
    inline void cb_Done_i(fltk::Button*, void*);
    static void cb_Done(fltk::Button*, void*);
public:
    fltk::Group *mFontWidget;
  LabelNodeMenu(pVisusLabelNode label) ;
  virtual ~LabelNodeMenu();
  bool isActive();
};
#endif
