// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef OrthoSliceMenu_h
#define OrthoSliceMenu_h
#include <fltk/Window.h>
#include "FLTKNodeMenu.h"
#include "VisusOrthogonalSlice.h"
#include <fltk/Button.h>
#include <fltk/Group.h>
#include <fltk/Choice.h>
#include <fltk/Item.h>

class OrthoSliceMenu : public FLTKNodeMenu<pVisusOrthogonalSlice>  {
public:
  fltk::Window* createWindow();
  fltk::Window *mMenuWindow;
private:
    inline void cb_Done_i(fltk::Button*, void*);
    static void cb_Done(fltk::Button*, void*);
public:
    fltk::Group *mColorMapWidget;
  OrthoSliceMenu(pVisusOrthogonalSlice slice) ;
  virtual ~OrthoSliceMenu();
  bool isActive();
};
#endif
