// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef TickMarksMenu_h
#define TickMarksMenu_h
#include <fltk/Window.h>
#include "FLTKNodeMenu.h"
#include "VisusTickMarks.h"
#include <fltk/Group.h>
#include <fltk/Button.h>

class TickMarksMenu : public FLTKNodeMenu<pVisusTickMarks>  {
public:
  TickMarksMenu(pVisusTickMarks node) ;
  virtual ~TickMarksMenu();
  fltk::Window* createWindow();
  fltk::Window *mMenuWindow;
    fltk::Group *mBorderAxisWidget;
private:
    inline void cb_Done_i(fltk::Button*, void*);
    static void cb_Done(fltk::Button*, void*);
public:
  bool isActive();
};
#endif
