packages = [ 
	    "Packages/AutoAPI",
            "Packages/cdtime",
            "Packages/regrid2",
#            "Packages/regrid",
            "Packages/Properties",
	    "Packages/kinds",
            "Packages/cdms2", 
            "Packages/genutil", 
            "Packages/cdutil", 
            "Packages/unidata", 
#            "Packages/cdms", 
            "Packages/ncml", 
            "Packages/esg",
            "Packages/distarray",
           ]
