#!/bin/sh
if ( test "$1" = "all" ) then
   (cd pysrc ; ./clean_script)
   (cd exsrc ; ./clean_script)
   (cd logs ; /bin/rm *.LOG)
fi

(cd libcdms;./clean_script >cdms.LOG 2>&1; /bin/rm -f cdms.LOG rebuild.py rebuild.LOG)
(cd esg; /bin/rm -fr build *.LOG rebuild.py *.log)
(cd Packages; /bin/rm -fr */build */rebuild.py */*.LOG */Test/Good */*.log)
(cd Packages/visus/src/pyvisus ; /bin/rm -rf build)
(cd contrib;/bin/rm -fr */build */*.o */*.a */*.pyc */Src/*.o */Src/*.a */rebuild.py */*.LOG */Test/Good */*.log)
/bin/rm -fr build *.pyc installation/build installation/cdat_info.* *~ rebuild.py 
find . -name 'config.cache' -print -exec rm {} \; 
