#!/bin/sh
if ( test "$1" = "all" ) then
   (cd pysrc >/dev/null ; ./clean_script)
   (cd exsrc >/dev/null; ./clean_script)
   (cd logs >/dev/null ; /bin/rm *.LOG >/dev/null 2>&1)
fi

(cd libcdms;./clean_script >cdms.LOG 2>&1; /bin/rm -f cdms.LOG rebuild.py rebuild.LOG >/dev/null 2>&1)
(cd esg; /bin/rm -fr build *.LOG rebuild.py *.log >/dev/null 2>&1)
(cd Packages; /bin/rm -fr vcs/cdatwrap */build */rebuild.py */*.LOG */Test/Good */*.log >/dev/null 2>&1)
(cd Packages/visus/src/pyvisus ; /bin/rm -rf build >/dev/null 2>&1)
(cd contrib;/bin/rm -fr */build */*.o */*.a */*.pyc */Src/*.o */Src/*.a */rebuild.py */*.LOG */Test/Good */*.log >/dev/null 2>&1)
/bin/rm -fr build *.pyc installation/build installation/cdat_info.* *~ rebuild.py  >/dev/null 2>&1
find . -name 'config.cache' -print -exec rm {} \; 
