#!/bin/sh


if (test -z "$1") then
    echo "Usage: $0 prefix";
    exit 1
fi

prefix=`(cd $1;pwd)`
if (test "$2" = "" ) then
  pyprefix=${prefix}
else
  pyprefix=`(cd $2;pwd)`
fi

echo "Installation to ${prefix}"
# Make sure /usr/bin/env etc. finds 'ourselves'
# We hardwire inside this script but Scientific Python
# do not have a --prefix option.
PATH="${prefix}/bin:${PATH}"; export PATH

#Sphinx
( ${pyprefix}/bin/easy_install sphinx \
)
