
set(g2clib_source "${CMAKE_CURRENT_BINARY_DIR}/build/g2clib")
set(g2clib_install "${CMAKE_INSTALL_PREFIX}")

ExternalProject_Add(g2clib
  DOWNLOAD_DIR ${CMAKE_CURRENT_BINARY_DIR}
  SOURCE_DIR ${g2clib_source}
  INSTALL_DIR ${g2clib_install}
  URL ${G2CLIB_URL}/${G2CLIB_GZ}
  URL_MD5 ${G2CLIB_MD5}
  BUILD_IN_SOURCE 1
  PATCH_COMMAND ""
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ${CMAKE_COMMAND} -Dmake=$(MAKE) -DWORKING_DIR=<SOURCE_DIR>/g2clib-${G2CLIB_VERSION} -P ${cdat_CMAKE_BINARY_DIR}/cdat_make_step.cmake
  INSTALL_COMMAND ${CMAKE_COMMAND} -DWORKING_DIR=<SOURCE_DIR>/g2clib-${G2CLIB_VERSION} -P ${cdat_CMAKE_BINARY_DIR}/cdat_install_step.cmake
  DEPENDS ${g2clib_DEPENDENCIES}
)
