
# Numexpr
#
set(Numexpr_source "${CMAKE_CURRENT_BINARY_DIR}/build/Numexpr")
#set(ENV{LD_LIBRARY_PATH} "/usr/common/usg/python/2.7.1/lib:$ENV{LD_LIBRARY_PATH}")
#message("PYTHON PATH IS"$ENV{PYTHONPATH})

ExternalProject_Add(Numexpr
  DOWNLOAD_DIR ${CMAKE_CURRENT_BINARY_DIR}
  SOURCE_DIR ${Numexpr_source}
  URL ${NUMEXPR_URL}/${NUMEXPR_GZ}
  URL_MD5 ${NUMEXPR_MD5}
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND ""
  BUILD_COMMAND env PYTHONPATH=$ENV{PYTHONPATH} LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH} ${PYTHON_EXECUTABLE} setup.py build
  INSTALL_COMMAND env PYTHONPATH=$ENV{PYTHONPATH} LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH} ${PYTHON_EXECUTABLE} setup.py install ${PYTHON_EXTRA_PREFIX}
  DEPENDS ${Numexpr_DEPENDENCIES}
  ${EP_LOG_OPTIONS}
  )
