#!/bin/bash

CTEST_UPDATE_COMMAND=$1
CTEST_SOURCE_DIRECTORY=$2
REPO=$3
BRANCH=$4

${CTEST_UPDATE_COMMAND} clone --recursive ${REPO} ${CTEST_SOURCE_DIRECTORY}
cd ${CTEST_SOURCE_DIRECTORY}
${CTEST_UPDATE_COMMAND} checkout ${BRANCH}
