## Provide information about this project
cmake_minimum_required(VERSION 2.8.7)

## Populate CMakeCache with block of initial data
file(
  # CMake settings
  WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" "
  CMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}
  DART_TESTING_TIMEOUT:STRING=1500
  UPDATE_TYPE:STRING=git
  ${PLATFORM_SPECIFIC_CACHE_DATA}
  CDAT_BUILD_ESMF_ESMP:BOOL=ON
  CDAT_BUILD_ESMF_PARALLEL:BOOL=ON
  CDAT_BUILD_PARAVIEW:BOOL=ON
  CDAT_BUILD_VISIT:BOOL=ON
  CDAT_DOWNLOADS_SAMPLE_DATA:BOOL=ON
  QT_QMAKE_EXECUTABLE:FILEPATH=$ENV{HOME}/qt-4.8.5/bin/qmake
")
