set(CFFI_MAJOR_SRC 0)
set(CFFI_MINOR_SRC 8)
set(CFFI_PATCH_SRC 2)

set(CFFI_VERSION ${CFFI_MAJOR_SRC}.${CFFI_MINOR_SRC}.${CFFI_PATCH_SRC})
set(CFFI_GZ cffi-${CFFI_VERSION}.tar.gz)
set(CFFI_SOURCE ${LLNL_URL}/${CFFI_GZ})
set(CFFI_MD5 37fc88c62f40d04e8a18192433f951ec)

add_cdat_package_dependent(CFFI "" "" ON "CDAT_BUILD_WO_ESGF" OFF)
