set(CFFI_MAJOR_SRC 1)
set(CFFI_MINOR_SRC 5)
set(CFFI_PATCH_SRC 2)

set(CFFI_VERSION ${CFFI_MAJOR_SRC}.${CFFI_MINOR_SRC}.${CFFI_PATCH_SRC})
set(CFFI_GZ cffi-${CFFI_VERSION}.tar.gz)
set(CFFI_SOURCE ${LLNL_URL}/${CFFI_GZ})
set(CFFI_MD5 fa766133f7299464c8bf857e0c966a82)

add_cdat_package_dependent(CFFI "" "" OFF "CDAT_BUILD_LEAN" ON)
