set(CRYPTOGRAPHY_MAJOR_SRC 1)
set(CRYPTOGRAPHY_MINOR_SRC 3)
set(CRYPTOGRAPHY_PATCH_SRC 2)

set(CRYPTOGRAPHY_VERSION ${CRYPTOGRAPHY_MAJOR_SRC}.${CRYPTOGRAPHY_MINOR_SRC}.${CRYPTOGRAPHY_PATCH_SRC})
set(CRYPTOGRAPHY_GZ cryptography-${CRYPTOGRAPHY_VERSION}.tar.gz)
set(CRYPTOGRAPHY_SOURCE ${LLNL_URL}/${CRYPTOGRAPHY_GZ})
set(CRYPTOGRAPHY_MD5 0359190f291824dc8ad9e6d477a607b2)

add_cdat_package_dependent(CRYPTOGRAPHY "" "" OFF "CDAT_BUILD_LEAN" OFF)
