set(CRYPTOGRAPHY_MAJOR_SRC 0)
set(CRYPTOGRAPHY_MINOR_SRC 4)
set(CRYPTOGRAPHY_PATCH_SRC 0)

set(CRYPTOGRAPHY_VERSION ${CRYPTOGRAPHY_MAJOR_SRC}.${CRYPTOGRAPHY_MINOR_SRC})
set(CRYPTOGRAPHY_GZ cryptography-${CRYPTOGRAPHY_VERSION}.tar.gz)
set(CRYPTOGRAPHY_SOURCE ${LLNL_URL}/${CRYPTOGRAPHY_GZ})
set(CRYPTOGRAPHY_MD5 d1bb13648a12eda2a54653ba113d2e84)

add_cdat_package_dependent(CRYPTOGRAPHY "" "" ON "CDAT_BUILD_WO_ESGF" OFF)
