set(eofs_MAJOR_SRC 1)
set(eofs_MINOR_SRC 1)
set(eofs_PATCH_SRC 0)
set(eofs_VERSION ${eofs_MAJOR_SRC}.${eofs_MINOR_SRC}.${eofs_PATCH_SRC})
set(eofs_URL ${LLNL_URL})
set(eofs_GZ eofs-${eofs_VERSION}.tar.gz)
set(eofs_MD5 52fce9f666d540069c90a6c109fcb3b4)
set(eofs_SOURCE ${eofs_URL}/${eofs_GZ})

add_cdat_package_dependent(eofs "" "" OFF "CDAT_BUILD_LEAN" ON)
