set( GDAL_MAJOR 1  )
set( GDAL_MINOR 11  )
set( GDAL_PATCH 2  )
set(GDAL_URL ${LLNL_URL})
set(GDAL_GZ gdal-${GDAL_MAJOR}.${GDAL_MINOR}.${GDAL_PATCH}.tar.gz)
set(GDAL_MD5 866a46f72b1feadd60310206439c1a76 )

set (nm GDAL)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_MAJOR}.${${nm}_MINOR}.${${nm}_PATCH})
set(GDAL_SOURCE ${GDAL_URL}/${GDAL_GZ})

if (CDAT_BUILD_ALL)
  add_cdat_package(gdal "" "Build the Geospatial Data Abstraction Library (GDAL) and python osgeo module" ON)
else()
  add_cdat_package(gdal "" "Build the Geospatial Data Abstraction Library (GDAL) and python osgeo module" OFF)
endif()
