set( GSW_MAJOR 3 )
set( GSW_MINOR 0 )
set( GSW_PATCH 3 )
set( GSW_VERSION ${GSW_MAJOR}.${GSW_MINOR}.${GSW_PATCH} )
set( GSW_URL ${LLNL_URL} )
set( GSW_GZ python-gsw-${SEAWATER_VERSION}.tar.gz )
set( GSW_MD5 a522a9ab6ab41fb70064e0378e904ffd )

set (nm GSW)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_MAJOR}.${${nm}_MINOR}.${${nm}_PATCH})
set(GSW_SOURCE ${GSW_URL}/${GSW_GZ})

if (CDAT_BUILD_ALL)
  add_cdat_package(gsw "" "" ON)
else()
  add_cdat_package(gsw "" "" OFF)
endif()
