set(IPADDRESS_MAJOR_SRC 1)
set(IPADDRESS_MINOR_SRC 0)
set(IPADDRESS_PATCH_SRC 16)

set(IPADDRESS_VERSION ${IPADDRESS_MAJOR_SRC}.${IPADDRESS_MINOR_SRC}.${IPADDRESS_PATCH_SRC})
set(IPADDRESS_GZ ipaddress-${IPADDRESS_VERSION}.tar.gz)
set(IPADDRESS_SOURCE ${LLNL_URL}/${IPADDRESS_GZ})
set(IPADDRESS_MD5 1e27b62aa20f5b6fc200b2bdbf0d0847)

add_cdat_package_dependent(IPADDRESS "" "" OFF "CDAT_BUILD_LEAN" OFF)
