set(IPYTHON_MAJOR 2)
set(IPYTHON_MINOR 1)
set(IPYTHON_PATCH 0)
set(IPYTHON_VERSION ${IPYTHON_MAJOR}.${IPYTHON_MINOR}.${IPYTHON_PATCH} )
set(IPYTHON_URL ${LLNL_URL})
set(IPYTHON_GZ ipython-${IPYTHON_VERSION}.tar.gz)
set(IPYTHON_MD5 785c7b6364c6a0dd34aa4ea970cf83b9)

set(IPYTHON_SOURCE ${IPYTHON_URL}/${IPYTHON_GZ})


add_cdat_package(IPYTHON "" "" ON)
