set(IPYTHON_MAJOR 2)
set(IPYTHON_MINOR 4)
set(IPYTHON_PATCH 1)
set(IPYTHON_VERSION ${IPYTHON_MAJOR}.${IPYTHON_MINOR}.${IPYTHON_PATCH} )
set(IPYTHON_URL ${LLNL_URL})
set(IPYTHON_GZ ipython-${IPYTHON_VERSION}.tar.gz)
set(IPYTHON_MD5 70149981d6515d77ecb3d7507de2d7d9)

set(IPYTHON_SOURCE ${IPYTHON_URL}/${IPYTHON_GZ})

add_cdat_package(IPYTHON "" "" ON)
