if (CDAT_BUILD_ALL)
  set(IPYTHON_deps ${pip_pkg} ${numpy_pkg} ${pyexpect_pkg} ${traitlets_pkg} ${tornado_pkg} ${numexpr_pkg})
else ()
  set(IPYTHON_deps ${pip_pkg} ${numpy_pkg} ${pyexpect_pkg} ${traitlets_pkg})
endif()
