ExternalProject_Add(IPYTHON
  DOWNLOAD_COMMAND ""
  WORKING_DIRECTORY ${CMAKE_INSTALL_PREFIX}
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND ""
  BUILD_COMMAND  ""
  INSTALL_COMMAND  ${PIP_BINARY} install ipython==${IPYTHON_VERSION}
  DEPENDS ${IPYTHON_deps}
  ${ep_log_options}
  )
