set(LIBCDMS_VERSION 1.0.0)
set(LIBCDMS_URL ${LLNL_URL})
set(LIBCDMS_GZ libcdms-${LIBCDMS_VERSION}.tar.gz)
set(LIBCDMS_SOURCE ${LIBCDMS_URL}/${LIBCDMS_GZ})
set(LIBCDMS_MD5 ce71f54616f755d67fbbb6c81ca4fd62)
set(LIBCDMS_BRANCH master)
set(LIBCDMS_REPOSITORY ${GIT_PROTOCOL}github.com/UV-CDAT/libcdms.git )

set(GIT_CMD_STR GIT_REPOSITORY ${LIBCDMS_REPOSITORY})
set(GIT_TAG GIT_TAG "${LIBCDMS_BRANCH}")

add_cdat_package(libcdms "" "" OFF)
