set(NUMEXPR_MAJOR 2)
set(NUMEXPR_MINOR 4)
set(NUMEXPR_PATCH 4)
#set(NUMEXPR_VERSION ${NUMEXPR_MAJOR}.${NUMEXPR_MINOR})
set(NUMEXPR_VERSION ${NUMEXPR_MAJOR}.${NUMEXPR_MINOR}.${NUMEXPR_PATCH})
# Following not needed any longer using easy_install
set(NUMEXPR_URL ${LLNL_URL})
set(NUMEXPR_GZ numexpr-${NUMEXPR_VERSION}.tar.gz)
set(NUMEXPR_MD5 5d62b029b6405317ab1f6dfa33da30fc)
set(NUMEXPR_SOURCE ${NUMEXPR_URL}/${NUMEXPR_GZ})

add_cdat_package(Numexpr "" "" OFF)
