set(PARAVIEW_MAJOR 3)
set(PARAVIEW_MINOR 11)
set(PARAVIEW_PATCH 1)
set(PARAVIEW_VERSION ${PARAVIEW_MAJOR}.${PARAVIEW_MINOR}.${PARAVIEW_PATCH})
set(PARAVIEW_URL ${LLNL_URL})
set(PARAVIEW_GZ ParaView-${PARAVIEW_VERSION}c.tar.gz)
set(PARAVIEW_MD5 81565b70093784dea38d2d62e072287b)

add_cdat_package_dependent(ParaView "" "Build ParaView" ON "CDAT_BUILD_GUI" OFF)
