set( PEP8_MAJOR 1 )
set( PEP8_MINOR 5 )
set( PEP8_PATCH 7)
set( PEP8_VERSION ${PEP8_MAJOR}.${PEP8_MINOR}.${PEP8_PATCH} )
set( PEP8_URL ${LLNL_URL} )
set( PEP8_GZ pep8-${PEP8_VERSION}.tar.gz )
set( PEP8_MD5 f6adbdd69365ecca20513c709f9b7c93 )

set (nm PEP8)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_MAJOR}.${${nm}_MINOR}.${${nm}_PATCH})
set(PEP8_SOURCE ${PEP8_URL}/${PEP8_GZ})

if (BUILD_TESTING)
  add_cdat_package(pep8 "" "" ON)
endif()
