set(PYCPARSER_MAJOR_SRC 2)
set(PYCPARSER_MINOR_SRC 13)
set(PYCPARSER_PATCH_SRC )

set(PYCPARSER_VERSION ${PYCPARSER_MAJOR_SRC}.${PYCPARSER_MINOR_SRC})
set(PYCPARSER_GZ pycparser-${PYCPARSER_VERSION}.tar.gz)
set(PYCPARSER_SOURCE ${LLNL_URL}/${PYCPARSER_GZ})
set(PYCPARSER_MD5 e4fe1a2d341b22e25da0d22f034ef32f )

add_cdat_package_dependent(PYCPARSER "" "" ON "CDAT_BUILD_LEAN" OFF)
