set(PYOPENSSL_MAJOR_SRC 0)
set(PYOPENSSL_MINOR_SRC 14)
set(PYOPENSSL_PATCH_SRC 0)

set(PYOPENSSL_VERSION ${PYOPENSSL_MAJOR_SRC}.${PYOPENSSL_MINOR_SRC})
set(PYOPENSSL_GZ pyOpenSSL-${PYOPENSSL_VERSION}.tar.gz)
set(PYOPENSSL_SOURCE ${LLNL_URL}/${PYOPENSSL_GZ})
set(PYOPENSSL_MD5 8579ff3a1d858858acfba5f046a4ddf7)

add_cdat_package_dependent(PYOPENSSL "" "" ON "CDAT_BUILD_WO_ESGF" OFF)
