set(PYOPENSSL_MAJOR_SRC 0)
set(PYOPENSSL_MINOR_SRC 13)
set(PYOPENSSL_PATCH_SRC 0)

set(PYOPENSSL_VERSION ${PYOPENSSL_MAJOR_SRC}.${PYOPENSSL_MINOR_SRC})
set(PYOPENSSL_GZ pyOpenSSL-${PYOPENSSL_VERSION}.tar.gz)
set(PYOPENSSL_SOURCE ${LLNL_URL}/${PYOPENSSL_GZ})
set(PYOPENSSL_MD5 767bca18a71178ca353dff9e10941929 )

add_cdat_package_dependent(PYOPENSSL "" "" ON "CDAT_BUILD_WO_ESGF" OFF)
