set(PYPARSING_MAJOR_SRC 2)
set(PYPARSING_MINOR_SRC 0)
set(PYPARSING_PATCH_SRC 2)

set(PYPARSING_VERSION ${PYPARSING_MAJOR_SRC}.${PYPARSING_MINOR_SRC}.${PYPARSING_PATCH_SRC})
set(PYPARSING_GZ pyparsing-${PYPARSING_VERSION}.tar.gz)
set(PYPARSING_SOURCE ${LLNL_URL}/${PYPARSING_GZ})
set(PYPARSING_MD5 b170c5d153d190df1a536988d88e95c1)

add_cdat_package_dependent(PYPARSING "" "" ON "CDAT_BUILD_LEAN" OFF)
