set(PYSPHARM_MAJOR 1)
set(PYSPHARM_MINOR 0)
set(PYSPHARM_PATCH 8)
set(PYSPHARM_VERSION ${PYSPHARM_MAJOR}.${PYSPHARM_MINOR}.${PYSPHARM_PATCH})
set(PYSPHARM_URL ${LLNL_URL})
set(PYSPHARM_GZ pyspharm-${PYSPHARM_VERSION}.tar.gz)
set(PYSPHARM_MD5 7b3a33dd3cbeaa4b8bf67ed5bd210931)
set(PYSPHARM_SOURCE ${PYSPHARM_URL}/${PYSPHARM_GZ})

if (CDAT_BUILD_ALL)
  add_cdat_package(pyspharm "" "" ON)
else()
  add_cdat_package(pyspharm "" "" OFF)
endif()
