set(SIP_MAJOR 4)
set(SIP_MINOR 12)
set(SIP_PATCH 1)
set(SIP_MAJOR_SRC 4)
set(SIP_MINOR_SRC 16)
set(SIP_PATCH_SRC 4)
set(SIP_VERSION ${SIP_MAJOR_SRC}.${SIP_MINOR_SRC}.${SIP_PATCH_SRC})
set(SIP_URL http://www.riverbankcomputing.com/static/Downloads/sip${SIP_MAJOR_SRC})
set(SIP_URL ${LLNL_URL})
set(SIP_GZ sip-${SIP_MAJOR_SRC}.${SIP_MINOR_SRC}.${SIP_PATCH_SRC}.tar.gz)
set(SIP_MD5 a9840670a064dbf8f63a8f653776fec9 )
set(SIP_SOURCE ${SIP_URL}/${SIP_GZ})

add_cdat_package_dependent(SIP "" "" OFF "CDAT_BUILD_GUI" OFF)
