set(SIX_MAJOR_SRC 1)
set(SIX_MINOR_SRC 9)
set(SIX_PATCH_SRC 0)

set(SIX_VERSION ${SIX_MAJOR_SRC}.${SIX_MINOR_SRC}.${SIX_PATCH_SRC})
set(SIX_GZ six-${SIX_VERSION}.tar.gz)
set(SIX_SOURCE ${LLNL_URL}/${SIX_GZ})
set(SIX_MD5 476881ef4012262dfc8adc645ee786c4)

add_cdat_package_dependent(SIX "" "" ON "CDAT_BUILD_LEAN" OFF)
