set(SPYDER_MAJOR_SRC 3)
set(SPYDER_MINOR_SRC 0)
set(SPYDER_PATCH_SRC 0b1)
set(SPYDER_URL ${LLNL_URL})
set(SPYDER_ZIP spyder-${SPYDER_MAJOR_SRC}.${SPYDER_MINOR_SRC}.${SPYDER_PATCH_SRC}.zip)
set(SPYDER_SOURCE ${SPYDER_URL}/${SPYDER_ZIP})
set(SPYDER_MD5 0bd7a60573a839f9c85dd7a3eef61b4e)

add_cdat_package_dependent(spyder "" "" OFF "CDAT_BUILD_GUI" OFF) 
