set(VACUMM_MAJOR 3) 
set(VACUMM_MINOR 0)
set(VACUMM_PATCH 0)
set(VACUMM_VERSION ${VACUMM_MAJOR}.${VACUMM_MINOR}.${VACUMM_PATCH})
set(VACUMM_URL ${LLNL_URL} )
set(VACUMM_GZ vacumm-${VACUMM_VERSION}.tar.gz)
set(VACUMM_MD5 b468fa72ddba9d0cd39d51164bef1dd4)

set (nm VACUMM)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_MAJOR}.${${nm}_MINOR}.${${nm}_PATCH})
set(VACUMM_SOURCE ${VACUMM_URL}/${VACUMM_GZ})

if (CDAT_BUILD_ALL)
  add_cdat_package(vacumm "" "" ON)
else()
  add_cdat_package(vacumm "" "" OFF)
endif()
