set(VISIT_MAJOR 2)
set(VISIT_MINOR 6)
set(VISIT_PATCH 0)
set(VISIT_VERSION ${VISIT_MAJOR}.${VISIT_MINOR}.${VISIT_PATCH})
set(VISIT_URL http://vis.lbl.gov/~visit)
set(VISIT_GZ visit${VISIT_VERSION}.tar.gz)
set(VISIT_MD5 cb7ff3e7d6e487a11786644a3b49331e )
set(VISIT_SOURCE ${VISIT_URL}/${VISIT_GZ})

add_cdat_package_dependent(VisIt "" "Build VisIt" OFF "CDAT_BUILD_GUI" OFF)
