set(ZMQ_MAJOR 4)
set(ZMQ_MINOR 0)
set(ZMQ_PATCH 4)
set(ZMQ_VERSION ${ZMQ_MAJOR}.${ZMQ_MINOR}.${ZMQ_PATCH})
set(ZMQ_URL ${LLNL_URL})
set(ZMQ_GZ zeromq-${ZMQ_VERSION}.tar.gz)
set(ZMQ_MD5 f3c3defbb5ef6cc000ca65e529fdab3b)
set(ZMQ_SOURCE ${ZMQ_URL}/${ZMQ_GZ})

add_cdat_package(ZMQ "" "" "")
